#!/bin/bash 

    java -classpath /home/alessio/Desktop/AI_Final_project/code/enhsp/src/:/home/alessio/Desktop/AI_Final_project/code/enhsp/libs/PPMaJal2.jar:/home/alessio/Desktop/AI_Final_project/code/enhsp/libs/* ENHSP "$@"
